### ISSUE TITLE
Deezer app is modifying MIME html to be associated with it

### ISSUE THREAD

**Issue by ginolhac** [aunetx/deezer-linux#13]
Hello,

Deezer when it is launched is modifying the file `~/.config/mimeapps.list` as follows:

```
[Default Applications]
text/tab-separated-values=rstudio.desktop
text/plain=rstudio.desktop
text/html=deezer-desktop.desktop
x-scheme-handler/http=firefox.desktop
x-scheme-handler/https=firefox.desktop
application/xhtml+xml=firefox.desktop
x-scheme-handler/dzr=deezer-desktop.desktop
x-scheme-handler/deezer=deezer-desktop.desktop
```
the culprit is this line `text/html=deezer-desktop.desktop`.
Then any HTML files I open goes into `deezer` and of course does not display.

 If I manually replaced by `text/html=firefox.desktop`
HTML files are again opened by FF.

Put if I close `deezer` and later opened it, the mime `text/html` is again associated to Deezer.

Do you know why this is happening?

Thanks!

Ubuntu 21.10 with Wayland
GNOME 40.4.0
deezer `5.30.170` install via `.deb` and `apt`

**Comment by aunetx** [comment]
Hello, and thank you for opening this!

I noticed this some days ago too, and this is quite annoying. I don't know where it comes from, in the desktop file there is `MimeType=x-scheme-handler/deezer;` which is required for the app to open `deezer://` links to authenticate; however it should not have any impact on other links, and especially on html files.

I will try to see where it comes from, from what you say it looks like it is the mimetype file is regenerated by the app itself (which should normally not happen). Does the problem still happen if you use flatpak?

**Comment by ginolhac** [comment]
To be honest, I am an old man and just discovered flatpak thanks to you. I am in my old habits of `apt`.
I can give a try when I figure out how this works ☺️
But, yes it is super annoying, it has no reason to also change the html MIME association. Weird.

**Comment by ginolhac** [comment]
Follow-up, this flatpak reminds me of `snap` and leave me also unconvinced. It looks nice, is supposed to be GUI and friendly but does not work as expected

```
The application dev.aunetx.deezer depends on runtimes from:
  https://aunetx.dev/deezer-linux/
Configure this as new remote 'deezer-linux' [Y/n]: 
error: The application dev.aunetx.deezer/x86_64/master requires the runtime org.freedesktop.Platform/x86_64/21.08 which was not found
```

googling this error is noting obvious. So I stick to `apt` and manually fix the MIME file for now

**Comment by adynemo** [comment]
There are more information here: https://github.com/electron/electron/issues/20382
It seems to be a bug with `xdg-settings` used by electron. This bug happened with other electron app like Signal Desktop. 
Anyway, it seems to be fixed with the most recent versions of electron. So, I guess it needs to be upgraded.

**Comment by aunetx** [comment]
Thank you very much, I will try to update the electron version, hopefully it does not break anything already working.

And @ginolhac, thank you for your report, it looks like you need to install the flathub runtime to install deezer:

```sh
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
```

And if the flatpak version is not convincing enough, I guess using apt is good too, although you won't have the auto-update mechanism! To be honest I don't use flatpak myself as I prefer using it from rpm (I use fedora), but hopefully all versions should be equivalent at some point.

**Comment by aunetx** [comment]
I'm sorry, updating electron version seems like a no-go, deezer won't launch with something more recent than electron 13...

**Comment by ginolhac** [comment]
thank you @aunetx , for the moment I am using deezer as one of the firefox tab since I have it always opened.
