### ISSUE TITLE
"Flow: play how you feel" not working

### ISSUE THREAD

**Issue by gree7** [aunetx/deezer-linux#16]
Deezer has a new feature "Flow: play how you feel":
![image](https://user-images.githubusercontent.com/997305/162191284-52235bb3-8cc0-44fa-8eab-fa9f1a7506cd.png)
which is not working. The icons are shown as generic albums and the play button does nothing:
![image](https://user-images.githubusercontent.com/997305/162191458-a0e5ecd4-e420-48b2-baec-fecd8be26003.png)

**Comment by aunetx** [comment]
I just released version 5.30.210, which fixes this :)

**Comment by gree7** [comment]
Works like a charm. Thanks a lot!
