### ISSUE TITLE
Option to disable systray?

### ISSUE THREAD

**Issue by pschloenzke** [aunetx/deezer-linux#18]
As a suggestion, I would find it very nice to have the option to disable minimize-to-systray or even better to disable the systray functionality completely. Especially on GNOME, where there is no systray by default, it is annoying to have deezer running in the background.
Or is there maybe some workaround to disable it?

In any case: Thank you for your work on this! :)

**Comment by aunetx** [comment]
Thank you for the suggestion, this could be done pretty easily by tweaking some patch, I will try to incorporate this soon!

**Comment by aunetx** [comment]
I added this, you can now simply run the app with `--disable-systray` as an argument!

(this will be included in next release very soon)

**Comment by pschloenzke** [comment]
Great! Thank you :)
