### ISSUE TITLE
After closing the main window, Deezer does not stay in the tray

### ISSUE THREAD

**Issue by gree7** [aunetx/deezer-linux#21]
After installing v5.30.220-1, the main window when closed quits the whole app (it does not stay in the tray). The tray icon is present and works if the app is open. In v5.30.210-1 after closing the main window Deezer stayed in the tray and played music.

I didn't find a way how to change the behavior back as it was in v5.30.210-1 in settings or by a command line parameter. 

Workaround: revert to v5.30.210-1.

Operating System: Kubuntu 21.10
KDE Plasma Version: 5.24.4
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.2
Kernel Version: 5.17.0-5.1-liquorix-amd64 (64-bit)
Graphics Platform: X11

**Comment by ShaolinAssassin** [comment]
Same issue here with the AppImage version of the app. 

LM 20.3-XFCE

**Comment by adynemo** [comment]
I think the problem is that this [patch](https://github.com/aunetx/deezer-linux/blob/b99c06389d67b2dec45d833d21fde09d8a7bcdde/patches/quit.patch) does not seem to be applied. When I look at the main.js file, the other patches are applied but not this one.
