### ISSUE TITLE
Flatpak xdg-open not working

### ISSUE THREAD

**Issue by eduardomozart** [aunetx/deezer-linux#25]
Hello,

I'm using Deepin Linux 20.6 and installed Deezer from Flatpak, but I can't login at app.

When I click at login, it opens my browser at Deezer login page but after I successfully provides my credentials the xdg-open action seems to do nothing.

I had to run it through terminal using the following command for it to login successfully (similar to AppImage):

```
flatpak run dev.aunetx.deezer deezer://autolog/...
```

**Comment by aunetx** [comment]
Hello, sorry for the delay. This is weird, as I also use flatpak and everything works fine (I logged in yesterday, and to my surprise there was no problem).

Does it still happen? And have you changed any of the flatpak settings?

**Comment by eduardomozart** [comment]
Hello @aunetx, thank you for your response. I'm not using neither Linux and Deezer anymore (I started using Windows and Spotify), so I can't test it right now and I'll close this issue as it maybe outdated related to the last Deepin and this package release.

**Comment by aunetx** [comment]
Ok thank you, no problem! I will see if anybody else have this problem.
