### ISSUE TITLE
Build deb file

### ISSUE THREAD

**Issue by samuelv8** [aunetx/deezer-linux#27]
Running installation commands like described returns an error.

```
$ make install_deps

added 17 packages, and audited 18 packages in 3s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

added 1 package, and audited 19 packages in 823ms

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Download installer
2022-08-03 19:45:22 URL:https://e-cdn-content.dzcdn.net/builds/deezer-desktop/8cF2rAuKxLcU1oMDmCYm8Uiqe19Ql0HTySLssdzLkQ9ZWHuDTp2JBtQOvdrFzWPA/win32/x86/5.30.220/DeezerDesktopSetup_5.30.220.exe [77848448/77848448] -> "source/deezer-setup-5.30.220.exe" [1]
Extract app archive from installer
/bin/sh: 1: 7z: not found
make: *** [Makefile:19: prepare] Error 127
```

Then when I try to run `make build_deb` returns an error "Command 'build-deb' not found." I'm on Ubuntu 20.04 LTS.

**Comment by adynemo** [comment]
Hello!

As you can see before the error `/bin/sh: 1: 7z: not found`, 7z is missing but required by the installation.
So you have to install it.

And as your installation failed, obviously the build_deb couldn't work.

**Comment by samuelv8** [comment]
Agreed, but why 7z is a dependency if I just want to generate a .deb file?

**Comment by adynemo** [comment]
Because to generate the deb file, the official app is downloaded and the sources are extracted from it. And for this extraction, 7z is required, as you can see here: https://github.com/aunetx/deezer-linux/blob/master/Makefile#L20
Maybe this step can be done in another way, I don't know.
At least, the 7z should be a requirement in the README.md

**Comment by aunetx** [comment]
You're correct, and I should have put it in the readme, sorry :)

Leaving this open until I correct it ^^
