### ISSUE TITLE
Outdated version

### ISSUE THREAD

**Issue by elsandosgrande** [aunetx/deezer-linux#28]
The latest version of the Windows application on the Deezer website is 5.30.330, whereas the latest version here is 5.30.220:

![image](https://user-images.githubusercontent.com/40576902/192223475-81484ce4-f5a8-4d0a-a342-989795459bef.png)

Though I can't say for certain, it seems that the application being out of date has finally caught up with it, because logging into the desktop application simply doesn't work as of today, whereas logging into the website works just fine:

https://user-images.githubusercontent.com/40576902/192224268-b02a4728-32f9-449b-807e-f99310d70759.mp4

**Comment by ShaolinAssassin** [comment]
Odd. I tried and could log out and log in back just fine. If that matters, I'm using the appimage version.

**Comment by elsandosgrande** [comment]
@ShaolinAssassin Huh, the AppImage works for me too. The above is the DEB package running on Ubuntu Jammy Jellyfish (22.04) by the way.

**Comment by aunetx** [comment]
Updated version :D

**Comment by aunetx** [comment]
(please tell me if an issue persists with the new version)

**Comment by elsandosgrande** [comment]
@aunetx So… The AppImage works fine now — it _used_ to work fine before, but then broke some time after I wrote that comment — but the DEB package still doesn't work for whatever reason. Also, I've upgraded to Ubuntu Kinetic in the meantime.
