### ISSUE TITLE
Can't connect with AppImage

### ISSUE THREAD

**Issue by Geordinateur** [aunetx/deezer-linux#29]
Hello, im using Archlinux,

`$ ./deezer-desktop-5.30.350-x86_64.AppImage deezer://autolog/...`
Im on page login

**Comment by ShaolinAssassin** [comment]
@Geordinateur replace the 3 dots with the numbers/letters given on that page, when you point your cursor on the "Open Deezer Music" button (see botton of the screenshot)
![Capture d’écran_2022-11-01_11-18-42](https://user-images.githubusercontent.com/22983718/199212943-5b51e92f-35d1-4af1-97e7-766f3c4034c5.png).

**Comment by aunetx** [comment]
Yes, you must first open the deezer application, and then call `./deezer-desktop-5.30.350-x86_64.AppImage deezer://autolog/...` with the link given in the screenshot.

By the way @ShaolinAssassin, you should not share your link as it would permit anybody to log into your account without password... But as your did not share the entire link it's okay right here ;)

**Comment by Geordinateur** [comment]
Ho great!, dont leave app when i launch `./deezer-desktop-5.30.350-x86_64.AppImage deezer://autolog/...`

Its works, thanks you!

**Comment by aunetx** [comment]
I added a link to this issue in the readme if needed for other people
