### ISSUE TITLE
How this works?

### ISSUE THREAD

**Issue by carrieroent** [aunetx/deezer-linux#34]
How this works? This isn't just Electron wrap for Deezer Web, this is a port of Deezer Windows to Linux, but it's closed source. And this doesn't use Wine? So how?

**Comment by aunetx** [comment]
Hello, this is just an automated way to depackage the proprietary deezer app for windows (which allows downloading etc) that uses electron, then I apply some patches to make it work well under linux, repackage it again and distribute it for different packages managers!

So no need to use Wine as the repackaged app is simply a native Linux app using electron, and yes the windows version is closed source... which means that all of this is only a bunch of hacks to have something working, sadly
