### ISSUE TITLE
Flow not shown in app

### ISSUE THREAD

**Issue by cstamas** [aunetx/deezer-linux#39]
Since today the 1st row where Flow is is not shown to me in the App, first row is "Your Favorite Artists".

When I go directly to deezer.com as logged in user, the Deezer UI looks "normal", Flow is there and "Your Favorite Artists" is 2nd row..

How come? How to listen to Flow in this app?

**Comment by Miikka69** [comment]
I noticed the same thing, that flow is missing!

**Comment by StollD** [comment]
I just updated the app to v5.30.570 myself, and after installing the new package the app looks exactly like the website.

**Comment by Miikka69** [comment]
But where can I get v5.30.570 when everything is still v5.30.520-1?

**Comment by StollD** [comment]
Either by editing the version number at the top of the Makefile and then building your own package, or by waiting for @aunetx to do that and make a new release.

**Comment by cstamas** [comment]
I still have no flow with this change https://github.com/aunetx/deezer-linux/pull/40

**Comment by StollD** [comment]
This is what it looks like for me. I am on Fedora 38 with deezer installed as an RPM package if that helps.

Since you said your first row is favourite artists, and my first row is what I listed to recently, could this be some country specific difference?

![deezer](https://github.com/aunetx/deezer-linux/assets/7887606/1b0842b3-d7f1-4dc3-911a-7dc5df5615ab)

**Comment by Miikka69** [comment]
![image](https://github.com/aunetx/deezer-linux/assets/67840836/a4254e6b-b76c-414b-bd41-d09e5663c18e)

**Comment by Miikka69** [comment]
![image](https://github.com/aunetx/deezer-linux/assets/67840836/466d7791-fefb-490a-bcb3-561b039125f0)
It can't be about the country, because the browser also shows flow

**Comment by cstamas** [comment]
For me, same as @Miikka69

**Comment by cstamas** [comment]
Wow, now rebuild rpm out of PR #40 and it WORKS for me as well.

Uninstalled flatpak one, as it anyway dragged some pretty old flatpak dependencies as well...

@Miikka69 can you rebuild rpm yourself? What OS are you on?

**Comment by StollD** [comment]
So this is weird. I just built the app as a flatpak (which was kinda tricky), and I also see flow with that. How did you build the flatpak after bumping the version number?

What I had to do was something like this:

```bash
$ rm -rf docs
$ flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
$ flatpak --user install org.freedesktop.Sdk org.electronjs.Electron2.BaseApp org.freedesktop.Sdk.Extension.node16
$ make export_flatpak # after editing out the GPG signing
$ flatpak build-bundle docs deezer.flatpak dev.aunetx.deezer
$ flatpak install deezer.flatpak
```

**Comment by cstamas** [comment]
I use flatpak, but did not built flatpak but AppImage version and it behaved 100% as (old) flatpak I had installed.... did not want to fiddle with flatpak env

**Comment by aunetx** [comment]
Sorry guys, updating this right now

**Comment by aunetx** [comment]
This seems fixed by last update, sorry for the delay

**Comment by Miikka69** [comment]
Thank you very much to everyone.
