### ISSUE TITLE
Publish to flathub

### ISSUE THREAD

**Issue by cstamas** [aunetx/deezer-linux#42]
That makes app more advertised and simpler to install: for example all "flathub enabled distros" I used (Mint, Fedora) have flathub enabled by default, so in case of F38 + Gnome, the software app would immediately show it, no CLI needed.

**Comment by aunetx** [comment]
I tried to upload this, however there are some legal points that may be problematic...

https://github.com/flathub/flathub/pull/4274

**Comment by aunetx** [comment]
It is published; it was faster than I though! see https://github.com/flathub/dev.aunetx.deezer

However, I still did not discussed about it with the deezer team... hope that will not be problematic

**Comment by aunetx** [comment]
It is published to flathub: https://github.com/flathub/dev.aunetx.deezer

I did not intend it to be so fast, I hope it won't be problematic for the deezer team
