### ISSUE TITLE
New icon

### ISSUE THREAD

**Issue by nclm** [aunetx/deezer-linux#49]
Deezer has a new logo, so the icon for this app should probably be updated to match?

Here is attached the icon used in the macOS version (as a 1024px PNG):

![Deezer](https://github.com/aunetx/deezer-linux/assets/923008/ae996051-3748-4fad-9cbf-e6b351735516)

**Comment by DanielRios549** [comment]
It is not only the icon, the app updates do version 6, with a new layout and color

**Comment by aunetx** [comment]
Hello, I am updating the app thanks to @MiMillieuh on #50, thanks a lot!
