### ISSUE TITLE
unable to log in

### ISSUE THREAD

**Issue by jum6076** [aunetx/deezer-linux#52]
Hello
Since upgrading to the latest version of the application, I can't connect. When I start the application, I click on the connect button. My browser connects to Deezer. Then I go back to the application, and it displays the message asking me to connect again. I get stuck on the login screen. 
![Capture d’écran du 2023-11-27 10-44-29](https://github.com/aunetx/deezer-linux/assets/109991397/a0ac268a-e8ba-4119-a9dc-38a20e7386f7)
I tried to uninstall the application and install it again, but it didn't work. I tried logging out from my browser so I'd need to re-enter my login details, but without success either. I use Firefox as browaser. I'm in ZorinOS 16.3. Before the latest update (v6.0.10-1) I'd never had this problem.
Thanks for your help

**Comment by TheTumultuousUnicornOfDarkness** [comment]
Same issue here.

But I found how to fix this issue: I deleted `~/.config/deezer-desktop` directory, now it works again.
