### ISSUE TITLE
Doesn't have dark mode

### ISSUE THREAD

**Issue by luismeza8** [aunetx/deezer-linux#6]
Is it normal that I can't find the dark mode option? will it be available in a future?

**Comment by aunetx** [comment]
No, it's not normal; it disappeared around a year ago when using linux, idk why... I will try to resolve it, but I've already tried and nothing came out of it

**Comment by VonKavalier** [comment]
I personally have it for some reason :shrug: 

![image](https://user-images.githubusercontent.com/21989855/145557411-9cb2867d-281f-414a-a231-996f9c3d6dff.png)

**Comment by florentdestremau** [comment]
Same here, it's available to me 
![image](https://user-images.githubusercontent.com/2852204/150300907-06c79d45-2e10-493e-bf6b-c8f5c4ca415b.png)
![image](https://user-images.githubusercontent.com/2852204/150300927-dd6c1fcf-067f-4cbc-989e-1dd35e132201.png)

Fresh install.

**Comment by aunetx** [comment]
Could you give me your specs? Like distro (Ubuntu probably I guess), DE...?

I don't know where it comes from, I should test with other DEs than gnome I guess

**Comment by Zalaxx** [comment]
It works perfectly fine for me too.
I'm using Pop!_Os 21.10 (with Gnome 40.4.0), deezer-linux installed with the .deb file.

**Comment by aunetx** [comment]
Ok thanks, maybe something is missing with fedora then if it seems to work under ubuntu! @luismeza8 which distro do you use?
